<?php

namespace AppBundle\Repository;

/**
 * WarehouseProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarehouseProductsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAvailable(){

        return $this->createQueryBuilder('wp')
            ->where('wp.quantity > 0')
            ->getQuery()
            ->getResult();
    }
}
